# Change these first
owner: whytspace # Your GitHub organization or username, where this repository lives
repo: regimed-status # The name of this repository

sites:
  - name: Homepage
    url: https://regimed.at

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.regimed.at
  baseUrl: /regimed-status
  logoUrl: https://raw.githubusercontent.com/whytspace/regimed-status/master/assets/regimed-icon.svg
  name: regimed Status
  navbar:
    - title: Website
      href: https://regimed.at
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
